name: Build and deploy Python app to Azure Web App 

on:
  push:
    branches:
      - main

jobs:
  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Set up Python version
  #       uses: actions/setup-python@v3
  #       with:
  #         python-version: '3.10'
      
  #     - name: Create and start virtual environment
  #       run: |
  #         python -m venv venv
  #         source venv/bin/activate
      
  #     - name: Install dependencies
  #       run: pip install -r requirements.txt
              
  #     - name: Upload artifact for deployment jobs
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: python-app
  #         path: |
  #           . 
  #           !venv/

  deploy:
    runs-on: ubuntu-latest
    # needs: build

    steps:
      - name: multiple command
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          password: ${{ secrets.AZURE_VM_PASSWORD }}
          port: ${{ secrets.AZURE_VM_PORT }}
          script: |
            cd ~/fastapi
            cd ./mtc-azure-openai-back
            git pull origin main
            source ./venv/bin/activate
            pip install -r requirements.txt
            ls -al
            systemctl restart openai.service